### ISSUE TITLE
SAP IS: Package Description and IFlow Description Not Updated

### ISSUE THREAD

**Issue by xprbj2212** [engswee/flashpipe-demo#2]
@engswee As we used Flashpipe to deploy Integration Content from Development to other environments . We observed package description, IFlow description which we have in development environment are not getting updated in other environments. 

Is this limitation of the API'  or do we need to maintain any metadata file to update descriptions while deploying to other environments. Please clarify?

**Comment by engswee** [comment]
This is the repository for the examples, so it's not the right place for raising issues. Please use https://github.com/engswee/flashpipe/issues instead, and also provide details of which version of flashpipe you are using, and the commands in your pipeline
